import { Course } from 'ingepro-entities';
import { FindOptionsSelect } from 'typeorm';

export const courseSelects = {
  base: (): FindOptionsSelect<Course> => ({
    curso_id: true,
    curso_codigo: true,
    curso_nombre: true,
    curso_descripcion: true,
    curso_dificultad: true,
    curso_horas_certificado: true,
    curso_precio_soles: true,
    curso_precio_soles_antes: true,
    curso_precio_dolar: true,
    curso_precio_dolar_antes: true,
    curso_imagen: true,
    curso_video_introductorio: true,
    curso_fecha_creacion: true,
    curso_fecha_fin: true,
    curso_fecha_inicio_publicacion: true,
    curso_fecha_fin_publicacion: true,
    curso_estado: true,
    curso_tiempo_acceso: true,
    curso_plantilla_certificado: true,
    curso_descripcion_certificado: true,
    curso_numero_inscritos: true,
    curso_tipo: true,
    curso_modalidad: true,
    curso_autor: true,
    curso_brochure: true,
    curso_fecha_inicio: true,
    curso_duracion: true,
    perfil_alumno: true,
    curso_portada: true,
    curso_link_whatsaap_grupo: true,
    curso_tipo_reproductor: true,
    curso_fecha_fin_evaluable: true,
  }),
  forCoupon: (): FindOptionsSelect<Course> => ({
    curso_id: true,
    curso_estado: true,
    curso_fecha_inicio: true,
    curso_imagen: true,
    curso_modalidad: true,
    curso_nombre: true,
    curso_portada: true,
    curso_precio_dolar: true,
    curso_precio_soles: true,
    curso_tipo: true,
    certificates: {
      certificado_id: true,
      certificado_costo_dolares: true,
      certificado_costo_soles: true,
      certificado_estado: true,
      envio_certificado_costo_soles: true,
      id_servicio: true,
      tipo_servicio: true,
      typeCertificate: {
        tipocert_estado: true,
        tipocert_nombre: true,
        tipocert_logo: true,
      },
    },
  }),
};
